# Generated by Django 2.2.6 on 2019-10-23 14:40

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Required. Inform a valid email address.', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Optional', max_length=30, null=True)),
                ('subject', models.CharField(blank=True, help_text='Optional', max_length=50, null=True)),
                ('message', models.TextField(help_text='A maximum of 1000 characters', max_length=1000)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Needs to be short and catchy. A maximum of 200 characters', max_length=200)),
                ('text', models.TextField()),
                ('post_picture', models.ImageField(upload_to='post_pictures/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='../static/images/user.png', upload_to=blog.models.user_pic_dir)),
                ('first_name', models.CharField(blank=True, help_text='A maximum of 30 characters', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, help_text='A maximum of 30 characters', max_length=30, null=True)),
                ('bio', models.TextField(blank=True, help_text='A maximum of 500 characters', max_length=500)),
                ('location', models.CharField(blank=True, help_text='A maximum of 30 characters', max_length=30)),
                ('birth_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD.', null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
