# Generated by Django 2.1 on 2018-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.IntegerField(choices=[('general', 'General enquiry'), ('bug', 'Bug report'), ('suggestion', 'Suggestion'), ('other', 'Other')], default=1)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
