# Generated by Django 2.1 on 2019-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_list',
            field=models.BooleanField(default=True),
        ),
    ]
