# Generated by Django 2.2.6 on 2019-10-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created',
            new_name='timestamp',
        ),
    ]
