# Generated by Django 2.1 on 2019-03-28 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='A maximum of 30 characters', max_length=30)),
                ('last_name', models.CharField(help_text='A maximum of 30 characters', max_length=30)),
                ('address', models.CharField(help_text='A maximum of 50 characters', max_length=50)),
                ('country', models.CharField(help_text='A maximum of 50 characters', max_length=50)),
                ('city', models.CharField(help_text='A maximum of 50 characters', max_length=50)),
                ('state', models.CharField(help_text='A maximum of 50 characters', max_length=50)),
                ('zip_code', models.DecimalField(decimal_places=0, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cart', models.ManyToManyField(blank=True, to='blog.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_list',
        ),
    ]
