# Generated by Django 2.1 on 2018-10-08 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.IntegerField(choices=[('select', '--Select a valid topic--'), ('general', 'General enquiry'), ('bug', 'Bug report'), ('suggestion', 'Suggestion'), ('other', 'Other')], default=1),
        ),
    ]
