# Generated by Django 2.1 on 2018-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181008_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.CharField(choices=[('general', 'General enquiry'), ('bug', 'Bug report'), ('suggestion', 'Suggestion'), ('other', 'Other')], default=1, max_length=30),
        ),
    ]
