# Generated by Django 2.1 on 2019-04-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postview',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
